catalog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('books/new', views.add_new_book, name='new-book'),
	path('books/all', views.BookListView.as_view(), name='books'),
	path('books/my', views.LoanedBooksByUserListView.as_view(), name='mybooks'),
	path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
	path('authors/new', views.add_new_author, name='new-author'),
	path('authors/all', views.AuthorListView.as_view(), name="authors"),
	path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

djlibrary/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

from rest_framework import routers
from .views import UserViewSet, GroupViewSet
# from notebook.views import NoteViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
# router.register(r'notes', NoteViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
	path('', include('catalog.urls')),
]

urlpatterns += [
	path('catalog/', include('catalog.urls')),
]

urlpatterns += [
	path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns += [
    path('', include('notebook.urls'))
]
"""
from django.views.generic import RedirectView

urlpatterns += [
	url(r'^$', RedirectView.as_view(url='/catalog/', permament=True)),
]
"""

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid

class Genre(models.Model):

    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name


class Language(models.Model):

    name = models.CharField(max_length=15)
    
    def __str__(self):
        return self.name


class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return "%s %s" % (self. first_name, self.last_name)


class Book(models.Model):

    title = models.CharField(max_length=200)
    authors = models.ManyToManyField(Author, null=True, blank=True, related_name='books')
    summary = models.TextField(max_length=1000)
    isbn = models.CharField('ISBN', max_length=13)
    genres = models.ManyToManyField(Genre, null=True, blank=True, related_name='books')
    lang = models.ManyToManyField(Language, null=True, blank=True, related_name='books')
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True) #!
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Обслуживание'),
        ('o', 'Выдана'),
        ('a', 'Доступна'),
        ('r', 'Забронирована'),
    )
    
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m')
    
    class Meta:
        ordering = ["due_back"]
    
    def __str__(self):
        return '%s - %s' % (self.id, self.book.title) # format py3
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

        
    def __str__(self):
        return '%s %s' % (self.last_name, self.first_name) # format py3
    
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

catalog/forms.py
from django import forms
from .models import Author, Book, Genre

#class AddNewAuthorForm(forms.Form):
#
#    first_name = forms.CharField()
#    last_name = forms.CharField()
#    date_of_birth = forms.DateField()
#    date_of_death = forms.DateField()

class AddNewAuthorForm(forms.ModelForm):

    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AddNewBookForm(forms.Form):

    title = forms.CharField(max_length=200)
    authors = forms.ModelMultipleChoiceField(Author.objects.all())
    summary = forms.CharField(widget=forms.Textarea)
    isbn = forms.CharField(max_length=13)
    genres = forms.ModelMultipleChoiceField(Genre.objects.all())

catalog/views.py
from django.shortcuts import render
import django.contrib.sessions

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User, Group
from django.http import HttpResponseRedirect

from rest_framework import viewsets

from .models import Book, Author, BookInstance, Genre
from .forms  import AddNewAuthorForm, AddNewBookForm
from .serializers import BookInstanceSerializer


def index(request):
	
	num_books = Book.objects.all().count()
	num_instances = BookInstance.objects.all().count()
	num_instances_available=BookInstance.objects.filter(status__exact='a').count()
	num_authors = Author.objects.all().count()
	
	num_visits = request.session.get('num_visits', 0)
	request.session['num_visits'] = num_visits + 1
	
	return render(
		request,
		'index.html',
		context={'num_books':num_books, 'num_instances':num_instances, 'num_instances_available':num_instances_available, 'num_authors':num_authors, 'num_visits':num_visits},
	)

class AuthorListView(ListView):
	model = Author

class AuthorDetailView(DetailView):
	model = Author

class BookListView(ListView):
	model = Book

class BookDetailView(DetailView):
	model = Book

class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
	model = BookInstance
	template_name ='catalog/bookinstance_list_borrowed_user.html'
	paginate_by = 10
	
	def get_queryset(self):
		return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

def add_new_author(request):

	form = AddNewAuthorForm(request.POST)

	if form.is_valid():
		form.save()

	return render(
		request,
		'catalog/add_new_author.html',
		context={'form': form},
	)

def add_new_book(request):

	form = AddNewBookForm()

	if request.method == 'POST':
		print(request.POST)
		print(request.POST.items())
		form = AddNewBookForm(request.POST)

		if form.is_valid():
			book = Book()
			book.title = form.cleaned_data['title']
			book.summary = form.cleaned_data['summary']
			book.isbn = form.cleaned_data['isbn']
			book.save()
			#import pdb; pdb.set_trace()
			for author in form.cleaned_data['authors']:
				book.authors.add(author)
			for genre in form.cleaned_data['genres']:
				book.genres.add(genre)
			#import pdb; pdb.set_trace()

			return HttpResponseRedirect(book.get_absolute_url())

	if request.method == 'GET':
		return render(
			request,
			'catalog/add_new_book.html',
			context={'form': form},
		)

catalog/templates/catalog/add_new_author.html
{% extends "base.html" %}
{% block title %}<title>Новый автор</title>{% endblock %}

{% block content %}

<h1>Добавление нового автора:</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Добавить">
</form>

{% endblock %}

catalog/templates/catalog/add_new_book.html
{% extends "base.html" %}
{% block title %}<title>Новая книга</title>{% endblock %}

{% block content %}

<h1>Добавление новой книги:</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Добавить">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
	<h1>{{ author.first_name}} {{author.last_name }}</h1>

	<p><strong>Дата рождения: </strong>{{ author.date_of_birth }}</p>

	{% if author.date_of_death %}
	<p><strong>Дата смерти: </strong>{{ author.date_of_death }}</p>
	{% endif %}

	</div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base.html" %}


{% block content %}

<h1>Список авторов:</h1>

{% if author_list %}
<ul>
	{% for author in author_list %}
	<li>
	<a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
	</li>
	{% endfor %}
</ul>
{% else %}
<p>Не найдено ни одного автора.
{% endif %}

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
	<h1>Информация о книге</h1>
	<h2>{{ book.title }}</h2>

	<p><strong>Автор:</strong> 
			{% for author in book.authors.all %}<a href="{{ author.get_absolute_url }}">{{ author }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
		</p>
	<p><strong>Описание:</strong> <p>{{ book.summary }}</p></p>
	<p><strong>ISBN:</strong> {{ book.isbn }}</p> 
	<p><strong>Язык:</strong> {{ book.language }}</p>  
	<p><strong>Жанр:</strong> {% for genre in book.genres.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}  </p>

	<div style="margin-left:20px;margin-top:20px">
		<h4>Копии:</h4>

		{% for copy in book.bookinstance_set.all %}
		<hr>
		<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
		{% if copy.status != 'a' %}<p><strong>Срок возврата:</strong> {{copy.due_back}}{% endif %}
		<p><strong>Номер копии:</strong> {{copy.imprint}}
		<p class="text-muted"><strong>ID:</strong> {{copy.id}}
		{% endfor %}
	</div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base.html" %}


{% block content %}

<h1>Список книг:</h1>

{% if book_list %}
<ul>
	{% for book in book_list %}
	<li>
	<a href="{{ book.get_absolute_url }}">{{ book.title }}</a> [{% for author in book.authors.all %} {{ author }}{% if not forloop.last %}, {% endif %}{% endfor %}]
	</li>
	{% endfor %}
</ul>
{% else %}
<p>Не найдено ни одной книги.
{% endif %}

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base.html" %}


{% block content %}

<h1>Список выданных в настоящий момент Вам книг:</h1>

{% if bookinstance_list %}

<ul>
	{% for bookinst in bookinstance_list %}
	<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
	<a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> (Автор -- {{ bookinst.book.authors }}) [Срок сдачи: {{ bookinst.due_back }}] 
	</li>
	{% endfor %}
</ul>
{% else %}
<p>Не найдено ни одной книги.

{% endif %}

{% endblock %}